const fs = require('fs');
const path = require('path');

// 50 Master Dummy Data Records - Exactly 50 items
const dummyData = [
  // 1-4: PT Telekom Mandiri Prima (4 contracts: 3 Active, 1 Expired)
  {
    vendor_id: "VND-1001",
    vendor_name: "PT Telekom Mandiri Prima",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Medium",
    result_selection: "Pass",
    rfc: "2026-01-15T09:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0001/DUMMY-TBG/VEM-SACME/01/I/2026",
    period: "2026",
    contract_date_from: "2026-01-01",
    contract_date_to: "2027-01-01",
    draft_sent_date: "2025-12-10",
    draft_return_date: "2025-12-28",
    final_approval_date: "2025-12-30",
    return_to_vendor_date: "2026-01-02",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-01-05",
    remarks_internal: "Kontrak payung SACME wilayah Jawa Bagian Barat",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1001",
    vendor_name: "PT Telekom Mandiri Prima",
    core_business: "PERKUATAN",
    vendor_category: "Medium",
    result_selection: "Pass",
    rfc: "2026-02-10T10:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0002/DUMMY-TBG/VEM-STR/02/II/2026",
    period: "2026",
    contract_date_from: "2026-02-01",
    contract_date_to: "2027-02-01",
    draft_sent_date: "2026-01-15",
    draft_return_date: "2026-01-25",
    final_approval_date: "2026-01-28",
    return_to_vendor_date: "2026-02-02",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-02-05",
    remarks_internal: "Pekerjaan perkuatan pondasi dan tower macro",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1001",
    vendor_name: "PT Telekom Mandiri Prima",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Medium",
    result_selection: "Pass",
    rfc: "2026-05-12T14:30:00.000Z",
    remarks_sourcing: "AMD",
    contract_type: "Amandemen",
    contract_number: "0003/AMD-01/TBG-SACME/05/V/2026",
    period: "2026",
    contract_date_from: "2026-05-01",
    contract_date_to: "2026-10-25", // Expiring in 60 days
    draft_sent_date: "2026-04-15",
    draft_return_date: "2026-04-25",
    final_approval_date: "2026-04-28",
    return_to_vendor_date: "2026-05-02",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: "Perlu konfirmasi adendum harga",
    action_status: "REMINDER 1",
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-09-20",
    remarks_internal: "Amandemen scope penambahan 25 site baru",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1001",
    vendor_name: "PT Telekom Mandiri Prima",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Medium",
    result_selection: "Pass",
    rfc: "2025-01-10T08:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0004/DUMMY-TBG/VEM-SACME/01/I/2025",
    period: "2025",
    contract_date_from: "2025-01-01",
    contract_date_to: "2025-12-31", // Expired
    draft_sent_date: "2024-12-15",
    draft_return_date: "2024-12-28",
    final_approval_date: "2024-12-30",
    return_to_vendor_date: "2025-01-05",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-01-05",
    remarks_internal: "Kontrak selesai tepat waktu",
    case_hold_terminate: null
  },

  // 5-7: PT Citra Daya Solusindo (3 contracts: 2 Active, 1 Expired)
  {
    vendor_id: "VND-1002",
    vendor_name: "PT Citra Daya Solusindo",
    core_business: "SUPPLY & INSTALL ICT",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-03-01T11:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0005/DUMMY-TBG/VEM-ICT/03/III/2026",
    period: "2026",
    contract_date_from: "2026-03-01",
    contract_date_to: "2027-03-01",
    draft_sent_date: "2026-02-10",
    draft_return_date: "2026-02-22",
    final_approval_date: "2026-02-27",
    return_to_vendor_date: "2026-03-02",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "contract.team@dummy-tbig.id",
    action_date: "2026-03-05",
    remarks_internal: "Supply & integrasi modul router radio microwave",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1002",
    vendor_name: "PT Citra Daya Solusindo",
    core_business: "SUPPLY & INSTALL ICT",
    vendor_category: "Small",
    result_selection: "Pass - Deviation",
    rfc: "2026-04-10T09:30:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "B",
    contract_number: "0006/DUMMY-TBG/VEM-ICT/04/IV/2026",
    period: "2026",
    contract_date_from: "2026-04-01",
    contract_date_to: "2026-11-15", // Expiring in 60 days
    draft_sent_date: "2026-03-12",
    draft_return_date: "2026-03-25",
    final_approval_date: "2026-03-29",
    return_to_vendor_date: "2026-04-02",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: "Follow up perpanjangan lisensi perangkat",
    action_status: "REMINDER 2",
    pic_email: "contract.team@dummy-tbig.id",
    action_date: "2026-09-15",
    remarks_internal: "Ada deviasi klausul SLA response time 4 jam",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1002",
    vendor_name: "PT Citra Daya Solusindo",
    core_business: "SUPPLY & INSTALL ICT",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2024-06-01T10:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "P",
    contract_number: "0007/DUMMY-TBG/VEM-ICT/06/VI/2024",
    period: "2024",
    contract_date_from: "2024-06-01",
    contract_date_to: "2025-06-01", // Expired
    draft_sent_date: "2024-05-15",
    draft_return_date: "2024-05-25",
    final_approval_date: "2024-05-28",
    return_to_vendor_date: "2024-06-02",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "contract.team@dummy-tbig.id",
    action_date: "2025-06-10",
    remarks_internal: "Arsip kontrak tahun 2024 selesai",
    case_hold_terminate: null
  },

  // 8-10: PT Fiber Optik Pratama (3 contracts: 3 Active)
  {
    vendor_id: "VND-1003",
    vendor_name: "PT Fiber Optik Pratama",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-01-20T10:15:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0008/DUMMY-TBG/VEM-FO/01/I/2026",
    period: "2026",
    contract_date_from: "2026-01-15",
    contract_date_to: "2027-01-15",
    draft_sent_date: "2025-12-18",
    draft_return_date: "2026-01-05",
    final_approval_date: "2026-01-10",
    return_to_vendor_date: "2026-01-16",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-01-20",
    remarks_internal: "Penarikan kabel FO area Jabodetabek dan Banten",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1003",
    vendor_name: "PT Fiber Optik Pratama",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-04-05T13:45:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "B",
    contract_number: "0009/DUMMY-TBG/VEM-FO/04/IV/2026",
    period: "2026",
    contract_date_from: "2026-04-01",
    contract_date_to: "2027-04-01",
    draft_sent_date: "2026-03-15",
    draft_return_date: "2026-03-24",
    final_approval_date: "2026-03-28",
    return_to_vendor_date: "2026-04-02",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-04-05",
    remarks_internal: "Project ekspansi backbone FO Jawa Tengah",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1003",
    vendor_name: "PT Fiber Optik Pratama",
    core_business: "FTTH & MAINTENANCE FTTH",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-06-15T09:00:00.000Z",
    remarks_sourcing: "AMD",
    contract_type: "Amandemen",
    contract_number: "0010/AMD-01/TBG-FTTH/06/VI/2026",
    period: "2026",
    contract_date_from: "2026-06-01",
    contract_date_to: "2027-06-01",
    draft_sent_date: "2026-05-10",
    draft_return_date: "2026-05-22",
    final_approval_date: "2026-05-28",
    return_to_vendor_date: "2026-06-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-06-05",
    remarks_internal: "Amandemen perluasan coverage FTTH residensial",
    case_hold_terminate: null
  },

  // 11-13: PT Mahakarya Telekomindo (3 contracts: 2 Active, 1 Expired)
  {
    vendor_id: "VND-1004",
    vendor_name: "PT Mahakarya Telekomindo",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Medium",
    result_selection: "Pass",
    rfc: "2026-02-18T10:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0011/DUMMY-TBG/VEM-SACME/02/II/2026",
    period: "2026",
    contract_date_from: "2026-02-15",
    contract_date_to: "2027-02-15",
    draft_sent_date: "2026-01-20",
    draft_return_date: "2026-02-05",
    final_approval_date: "2026-02-10",
    return_to_vendor_date: "2026-02-16",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-02-20",
    remarks_internal: "Pekerjaan sipil mechanical electrical wilayah Jawa Timur",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1004",
    vendor_name: "PT Mahakarya Telekomindo",
    core_business: "SUPPLY, INSTALL & DISMANTEL TOWER",
    vendor_category: "Medium",
    result_selection: "Pass - Deviation",
    rfc: "2026-05-02T11:20:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "B",
    contract_number: "0012/DUMMY-TBG/VEM-TWR/05/V/2026",
    period: "2026",
    contract_date_from: "2026-05-01",
    contract_date_to: "2026-11-20", // Expiring in 60 days
    draft_sent_date: "2026-04-10",
    draft_return_date: "2026-04-22",
    final_approval_date: "2026-04-27",
    return_to_vendor_date: "2026-05-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: "Pengecekan sertifikat kelaikan crane dismantle",
    action_status: "REMINDER 1",
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-09-18",
    remarks_internal: "Dismantel 10 tower relokasi tol Trans Jawa",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1004",
    vendor_name: "PT Mahakarya Telekomindo",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Medium",
    result_selection: "Pass",
    rfc: "2025-02-01T08:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "P",
    contract_number: "0013/DUMMY-TBG/VEM-SACME/02/II/2025",
    period: "2025",
    contract_date_from: "2025-02-01",
    contract_date_to: "2026-02-01", // Expired
    draft_sent_date: "2025-01-10",
    draft_return_date: "2025-01-22",
    final_approval_date: "2025-01-26",
    return_to_vendor_date: "2025-02-03",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-02-05",
    remarks_internal: "Kontrak telah diperpanjang dengan nomor baru",
    case_hold_terminate: null
  },

  // 14-15: PT Sinergi Tower Nusantara (2 contracts: 1 Active, 1 Expired)
  {
    vendor_id: "VND-1005",
    vendor_name: "PT Sinergi Tower Nusantara",
    core_business: "SUPPLY, INSTALL & DISMANTEL TOWER",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-03-10T14:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0014/DUMMY-TBG/VEM-TWR/03/III/2026",
    period: "2026",
    contract_date_from: "2026-03-01",
    contract_date_to: "2027-03-01",
    draft_sent_date: "2026-02-15",
    draft_return_date: "2026-02-24",
    final_approval_date: "2026-02-27",
    return_to_vendor_date: "2026-03-02",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "evaluasi.mitra@dummy-tbig.id",
    action_date: "2026-03-05",
    remarks_internal: "Ereksi tower SST 4 leg dan monopole",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1005",
    vendor_name: "PT Sinergi Tower Nusantara",
    core_business: "SUPPLY, INSTALL & DISMANTEL TOWER",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2024-03-01T09:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0015/DUMMY-TBG/VEM-TWR/03/III/2024",
    period: "2024",
    contract_date_from: "2024-03-01",
    contract_date_to: "2025-03-01", // Expired
    draft_sent_date: "2024-02-10",
    draft_return_date: "2024-02-22",
    final_approval_date: "2024-02-26",
    return_to_vendor_date: "2024-03-03",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "evaluasi.mitra@dummy-tbig.id",
    action_date: "2025-03-05",
    remarks_internal: "Batch pengadaan tower Sumatera 2024",
    case_hold_terminate: null
  },

  // 16-17: PT Bintang Telekomunikasi Indonesia (2 contracts: 2 Active)
  {
    vendor_id: "VND-1006",
    vendor_name: "PT Bintang Telekomunikasi Indonesia",
    core_business: "MAINTENANCE",
    vendor_category: "Medium",
    result_selection: "Pass",
    rfc: "2026-01-05T09:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0016/DUMMY-TBG/VEM-MNT/01/I/2026",
    period: "2026",
    contract_date_from: "2026-01-01",
    contract_date_to: "2027-01-01",
    draft_sent_date: "2025-12-12",
    draft_return_date: "2025-12-24",
    final_approval_date: "2025-12-28",
    return_to_vendor_date: "2026-01-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "ops.maintenance@dummy-tbig.id",
    action_date: "2026-01-08",
    remarks_internal: "Maintenance preventif & korektif site Jawa Tengah",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1006",
    vendor_name: "PT Bintang Telekomunikasi Indonesia",
    core_business: "MAINTENANCE",
    vendor_category: "Medium",
    result_selection: "Pass",
    rfc: "2026-04-18T10:00:00.000Z",
    remarks_sourcing: "AMD",
    contract_type: "Amandemen",
    contract_number: "0017/AMD-01/TBG-MNT/04/IV/2026",
    period: "2026",
    contract_date_from: "2026-04-01",
    contract_date_to: "2027-04-01",
    draft_sent_date: "2026-03-15",
    draft_return_date: "2026-03-26",
    final_approval_date: "2026-03-29",
    return_to_vendor_date: "2026-04-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "ops.maintenance@dummy-tbig.id",
    action_date: "2026-04-05",
    remarks_internal: "Penyesuaian checklist berkala genset & AC shelter",
    case_hold_terminate: null
  },

  // 18-19: CV Mitra Mandiri Abadi (2 contracts: 1 Active, 1 Expired)
  {
    vendor_id: "VND-1007",
    vendor_name: "CV Mitra Mandiri Abadi",
    core_business: "PERKUATAN",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-05-15T08:30:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0018/DUMMY-TBG/VEM-STR/05/V/2026",
    period: "2026",
    contract_date_from: "2026-05-01",
    contract_date_to: "2026-10-31", // Expiring in 60 days
    draft_sent_date: "2026-04-12",
    draft_return_date: "2026-04-20",
    final_approval_date: "2026-04-25",
    return_to_vendor_date: "2026-05-02",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: "Menunggu BAST perkuatan bracings 4 site",
    action_status: "REMINDER 1",
    pic_email: "contract.team@dummy-tbig.id",
    action_date: "2026-09-12",
    remarks_internal: "Perkuatan struktur besi siku dan tie rod tower",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1007",
    vendor_name: "CV Mitra Mandiri Abadi",
    core_business: "PERKUATAN",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2025-04-01T10:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0019/DUMMY-TBG/VEM-STR/04/IV/2025",
    period: "2025",
    contract_date_from: "2025-04-01",
    contract_date_to: "2025-11-30", // Expired
    draft_sent_date: "2025-03-10",
    draft_return_date: "2025-03-20",
    final_approval_date: "2025-03-25",
    return_to_vendor_date: "2025-04-03",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "contract.team@dummy-tbig.id",
    action_date: "2025-12-05",
    remarks_internal: "Pekerjaan tuntas",
    case_hold_terminate: null
  },

  // 20-21: PT Graha Primatama Sinergi (2 contracts: 1 Active, 1 Expired)
  {
    vendor_id: "VND-1008",
    vendor_name: "PT Graha Primatama Sinergi",
    core_business: "DESAIN, SUPPLY & INSTALASI IBS",
    vendor_category: "Medium",
    result_selection: "Pass",
    rfc: "2026-02-01T11:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0020/DUMMY-TBG/VEM-IBS/02/II/2026",
    period: "2026",
    contract_date_from: "2026-02-01",
    contract_date_to: "2027-02-01",
    draft_sent_date: "2026-01-10",
    draft_return_date: "2026-01-22",
    final_approval_date: "2026-01-27",
    return_to_vendor_date: "2026-02-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "ibs.procurement@dummy-tbig.id",
    action_date: "2026-02-08",
    remarks_internal: "Instalasi IBS gedung perkantoran dan mall tier-1 Jakarta",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1008",
    vendor_name: "PT Graha Primatama Sinergi",
    core_business: "DESAIN, SUPPLY & INSTALASI IBS",
    vendor_category: "Medium",
    result_selection: "Pass - Deviation",
    rfc: "2025-03-01T09:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0021/DUMMY-TBG/VEM-IBS/03/III/2025",
    period: "2025",
    contract_date_from: "2025-03-01",
    contract_date_to: "2026-03-01", // Expired
    draft_sent_date: "2025-02-12",
    draft_return_date: "2025-02-24",
    final_approval_date: "2025-02-27",
    return_to_vendor_date: "2025-03-05",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "ibs.procurement@dummy-tbig.id",
    action_date: "2026-03-10",
    remarks_internal: "Proyek IBS Bandara Internasional",
    case_hold_terminate: null
  },

  // 22-23: PT Nusantara Global Solusi (2 contracts: 2 Active)
  {
    vendor_id: "VND-1009",
    vendor_name: "PT Nusantara Global Solusi",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-05-10T10:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0022/DUMMY-TBG/VEM-FO/05/V/2026",
    period: "2026",
    contract_date_from: "2026-05-01",
    contract_date_to: "2027-05-01",
    draft_sent_date: "2026-04-12",
    draft_return_date: "2026-04-24",
    final_approval_date: "2026-04-28",
    return_to_vendor_date: "2026-05-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-05-08",
    remarks_internal: "Penggelaran FO jalur arteri Surabaya - Malang",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1009",
    vendor_name: "PT Nusantara Global Solusi",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-08-01T09:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0023/DUMMY-TBG/VEM-FO/08/VIII/2026",
    period: "2026",
    contract_date_from: "2026-08-01",
    contract_date_to: "2027-08-01",
    draft_sent_date: "2026-07-10",
    draft_return_date: "2026-07-22",
    final_approval_date: "2026-07-28",
    return_to_vendor_date: "2026-08-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-08-08",
    remarks_internal: "FO mikroducting area perkotaan",
    case_hold_terminate: null
  },

  // 24-25: PT Cipta Kreasi Konstruksi (2 contracts: 1 Active, 1 Expired)
  {
    vendor_id: "VND-1010",
    vendor_name: "PT Cipta Kreasi Konstruksi",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-06-01T10:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0024/DUMMY-TBG/VEM-SACME/06/VI/2026",
    period: "2026",
    contract_date_from: "2026-06-01",
    contract_date_to: "2027-06-01",
    draft_sent_date: "2026-05-15",
    draft_return_date: "2026-05-25",
    final_approval_date: "2026-05-29",
    return_to_vendor_date: "2026-06-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-06-08",
    remarks_internal: "Pembangunan site rooftop micro cell",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1010",
    vendor_name: "PT Cipta Kreasi Konstruksi",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2024-05-01T09:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0025/DUMMY-TBG/VEM-SACME/05/V/2024",
    period: "2024",
    contract_date_from: "2024-05-01",
    contract_date_to: "2025-05-01", // Expired
    draft_sent_date: "2024-04-12",
    draft_return_date: "2024-04-24",
    final_approval_date: "2024-04-28",
    return_to_vendor_date: "2024-05-05",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2025-05-10",
    remarks_internal: "Selesai kontrak awal",
    case_hold_terminate: null
  },

  // 26-38: 13 Active Single Contracts
  {
    vendor_id: "VND-1011",
    vendor_name: "PT Sarana Jaringan Bersama",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-01-10T10:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0026/DUMMY-TBG/VEM-FO/01/I/2026",
    period: "2026",
    contract_date_from: "2026-01-01",
    contract_date_to: "2026-12-31", // Des 2026
    draft_sent_date: "2025-12-10",
    draft_return_date: "2025-12-22",
    final_approval_date: "2025-12-28",
    return_to_vendor_date: "2026-01-04",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-01-08",
    remarks_internal: "Instalasi OSP FO Sumatera Utara",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1012",
    vendor_name: "PT Selaras Daya Utomo",
    core_business: "MAINTENANCE",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-07-01T09:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0027/DUMMY-TBG/VEM-MNT/07/VII/2026",
    period: "2026",
    contract_date_from: "2026-07-01",
    contract_date_to: "2027-07-01", // Jul 2027
    draft_sent_date: "2026-06-12",
    draft_return_date: "2026-06-22",
    final_approval_date: "2026-06-27",
    return_to_vendor_date: "2026-07-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "ops.maintenance@dummy-tbig.id",
    action_date: "2026-07-05",
    remarks_internal: "Pemeliharaan power sistem rectifier dan baterai lithium",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1013",
    vendor_name: "CV Cemerlang Tehnik",
    core_business: "PERKUATAN",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-03-20T10:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0028/DUMMY-TBG/VEM-STR/03/III/2026",
    period: "2026",
    contract_date_from: "2026-03-15",
    contract_date_to: "2026-11-28", // Expiring in 60 days
    draft_sent_date: "2026-02-25",
    draft_return_date: "2026-03-05",
    final_approval_date: "2026-03-10",
    return_to_vendor_date: "2026-03-17",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: "Menunggu final checklist NDT test",
    action_status: "REMINDER 2",
    pic_email: "contract.team@dummy-tbig.id",
    action_date: "2026-09-22",
    remarks_internal: "Pekerjaan perkuatan pondasi bore pile",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1014",
    vendor_name: "PT Mega Surya Elektrika",
    core_business: "SUPPLY & INSTALL ICT",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-01-25T11:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0029/DUMMY-TBG/VEM-ICT/01/I/2026",
    period: "2026",
    contract_date_from: "2026-01-20",
    contract_date_to: "2027-01-20", // Jan 2027
    draft_sent_date: "2025-12-20",
    draft_return_date: "2026-01-08",
    final_approval_date: "2026-01-15",
    return_to_vendor_date: "2026-01-22",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "contract.team@dummy-tbig.id",
    action_date: "2026-01-25",
    remarks_internal: "Instalasi perangkat solar cell hybrid panel",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1015",
    vendor_name: "PT Inti Data Telekomunikasi",
    core_business: "FTTH & MAINTENANCE FTTH",
    vendor_category: "Medium",
    result_selection: "Pass",
    rfc: "2026-04-01T10:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0030/DUMMY-TBG/VEM-FTTH/04/IV/2026",
    period: "2026",
    contract_date_from: "2026-04-01",
    contract_date_to: "2027-04-01", // Apr 2027
    draft_sent_date: "2026-03-10",
    draft_return_date: "2026-03-20",
    final_approval_date: "2026-03-26",
    return_to_vendor_date: "2026-04-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-04-06",
    remarks_internal: "Homepass FTTH cluster perumahan Bali & Lombok",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1016",
    vendor_name: "PT Kharisma Cahaya Persada",
    core_business: "ESR & SCSR",
    vendor_category: "Small",
    result_selection: "Pass - Deviation",
    rfc: "2026-02-15T09:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0031/DUMMY-TBG/VEM-ESR/02/II/2026",
    period: "2026",
    contract_date_from: "2026-02-10",
    contract_date_to: "2026-11-10", // Expiring in 60 days
    draft_sent_date: "2026-01-18",
    draft_return_date: "2026-01-29",
    final_approval_date: "2026-02-05",
    return_to_vendor_date: "2026-02-12",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: "Proses renegosiasi renewal tahun 2027",
    action_status: "REMINDER 3",
    pic_email: "evaluasi.mitra@dummy-tbig.id",
    action_date: "2026-09-25",
    remarks_internal: "Sertifikasi soil test & resistansi grounding",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1017",
    vendor_name: "PT Karya Prima Mandiri",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-05-10T11:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0032/DUMMY-TBG/VEM-SACME/05/V/2026",
    period: "2026",
    contract_date_from: "2026-05-01",
    contract_date_to: "2027-05-01", // Mei 2027
    draft_sent_date: "2026-04-10",
    draft_return_date: "2026-04-21",
    final_approval_date: "2026-04-26",
    return_to_vendor_date: "2026-05-02",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-05-05",
    remarks_internal: "Pekerjaan sipil Greenfield Tower Sulawesi",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1018",
    vendor_name: "PT Surya Citra Perkasa",
    core_business: "DESIGN DAN ANALISA KONSTRUKSI",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-03-01T10:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0033/DUMMY-TBG/VEM-ENG/03/III/2026",
    period: "2026",
    contract_date_from: "2026-03-01",
    contract_date_to: "2027-03-01", // Mar 2027
    draft_sent_date: "2026-02-10",
    draft_return_date: "2026-02-20",
    final_approval_date: "2026-02-25",
    return_to_vendor_date: "2026-03-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "engineering@dummy-tbig.id",
    action_date: "2026-03-06",
    remarks_internal: "Kajian analisis beban struktur dan loading wind calculation",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1019",
    vendor_name: "PT Tri Manunggal Sejahtera",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-04-12T14:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0034/DUMMY-TBG/VEM-FO/04/IV/2026",
    period: "2026",
    contract_date_from: "2026-04-01",
    contract_date_to: "2026-10-15", // Expiring in 60 days
    draft_sent_date: "2026-03-12",
    draft_return_date: "2026-03-24",
    final_approval_date: "2026-03-28",
    return_to_vendor_date: "2026-04-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "BELUM", // Scan belum
    upload_contract_status: "SUDAH",
    outstanding_status: "Menunggu pengiriman dokumen fisik bertandatangan basah",
    action_status: "REMINDER 1",
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-09-20",
    remarks_internal: "Penggelaran aerial cable jalur lintas selatan",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1020",
    vendor_name: "PT Multi Solusi Integrasi",
    core_business: "SUPPLY & INSTALL ICT",
    vendor_category: "Medium",
    result_selection: "Pass",
    rfc: "2026-02-25T11:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0035/DUMMY-TBG/VEM-ICT/02/II/2026",
    period: "2026",
    contract_date_from: "2026-02-15",
    contract_date_to: "2027-02-15", // Feb 2027
    draft_sent_date: "2026-01-20",
    draft_return_date: "2026-02-01",
    final_approval_date: "2026-02-08",
    return_to_vendor_date: "2026-02-17",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "contract.team@dummy-tbig.id",
    action_date: "2026-02-20",
    remarks_internal: "Pengadaan rack enclosure dan UPS 10kVA",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1021",
    vendor_name: "PT Wahana Telekomunikasi Unggul",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-07-10T10:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0036/DUMMY-TBG/VEM-SACME/07/VII/2026",
    period: "2026",
    contract_date_from: "2026-07-01",
    contract_date_to: "2027-07-01", // Jul 2027
    draft_sent_date: "2026-06-10",
    draft_return_date: "2026-06-20",
    final_approval_date: "2026-06-25",
    return_to_vendor_date: "2026-07-02",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-07-05",
    remarks_internal: "Batch 10 new site Kalimantan Timur (IKN buffer)",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1023",
    vendor_name: "PT Adhi Sarana Fiber",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-08-15T11:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0037/DUMMY-TBG/VEM-FO/08/VIII/2026",
    period: "2026",
    contract_date_from: "2026-08-01",
    contract_date_to: "2027-08-01", // Agu 2027
    draft_sent_date: "2026-07-15",
    draft_return_date: "2026-07-24",
    final_approval_date: "2026-07-29",
    return_to_vendor_date: "2026-08-03",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-08-06",
    remarks_internal: "Instalasi OSP FO route Semarang - Solo",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1031",
    vendor_name: "PT Bina Sarana Konstruksi",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-09-01T09:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0038/DUMMY-TBG/VEM-SACME/09/IX/2026",
    period: "2026",
    contract_date_from: "2026-09-01",
    contract_date_to: "2027-09-01", // Sep 2027
    draft_sent_date: "2026-08-10",
    draft_return_date: "2026-08-20",
    final_approval_date: "2026-08-26",
    return_to_vendor_date: "2026-09-02",
    contract_status: "Active",
    subcont_status: "active",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: null,
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-09-05",
    remarks_internal: "Pondasi pad and chimney site baru area DI Yogyakarta",
    case_hold_terminate: null
  },

  // 39-48: 10 Expired Single Contracts
  {
    vendor_id: "VND-1033",
    vendor_name: "PT Kencana Tower Mandiri",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2025-01-15T09:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0039/DUMMY-TBG/VEM-SACME/01/I/2025",
    period: "2025",
    contract_date_from: "2025-01-01",
    contract_date_to: "2025-12-31", // Expired
    draft_sent_date: "2024-12-10",
    draft_return_date: "2024-12-24",
    final_approval_date: "2024-12-29",
    return_to_vendor_date: "2025-01-05",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2026-01-02",
    remarks_internal: "Masa kontrak selesai, tidak diperpanjang karena evaluasi C",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1034",
    vendor_name: "CV Prima Sentosa",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2025-03-01T10:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0040/DUMMY-TBG/VEM-FO/03/III/2025",
    period: "2025",
    contract_date_from: "2025-03-01",
    contract_date_to: "2026-03-01", // Expired
    draft_sent_date: "2025-02-12",
    draft_return_date: "2025-02-22",
    final_approval_date: "2025-02-27",
    return_to_vendor_date: "2025-03-04",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-03-05",
    remarks_internal: "Pekerjaan tuntas 100%",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1035",
    vendor_name: "PT Surya Global Teknik",
    core_business: "MAINTENANCE",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2025-05-10T11:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0041/DUMMY-TBG/VEM-MNT/05/V/2025",
    period: "2025",
    contract_date_from: "2025-05-01",
    contract_date_to: "2026-05-01", // Expired
    draft_sent_date: "2025-04-15",
    draft_return_date: "2025-04-26",
    final_approval_date: "2025-04-29",
    return_to_vendor_date: "2025-05-03",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "ops.maintenance@dummy-tbig.id",
    action_date: "2026-05-05",
    remarks_internal: "Kontrak pemeliharaan berakhir",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1036",
    vendor_name: "PT Buana Cipta Mandiri",
    core_business: "SUPPLY & INSTALL ICT",
    vendor_category: "Small",
    result_selection: "Pass - Deviation",
    rfc: "2024-08-01T09:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0042/DUMMY-TBG/VEM-ICT/08/VIII/2024",
    period: "2024",
    contract_date_from: "2024-08-01",
    contract_date_to: "2025-08-01", // Expired
    draft_sent_date: "2024-07-15",
    draft_return_date: "2024-07-25",
    final_approval_date: "2024-07-29",
    return_to_vendor_date: "2024-08-04",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "contract.team@dummy-tbig.id",
    action_date: "2025-08-05",
    remarks_internal: "Pengadaan rack battery tahun 2024",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1037",
    vendor_name: "PT Mega Pratama Konstruksi",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2024-11-01T10:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0043/DUMMY-TBG/VEM-SACME/11/XI/2024",
    period: "2024",
    contract_date_from: "2024-11-01",
    contract_date_to: "2025-11-01", // Expired
    draft_sent_date: "2024-10-10",
    draft_return_date: "2024-10-22",
    final_approval_date: "2024-10-28",
    return_to_vendor_date: "2024-11-04",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "BELUM", // Scan belum
    upload_contract_status: "SUDAH",
    outstanding_status: "File scan hilang di arsip fisik lama",
    action_status: "INACTIVE",
    pic_email: "procurement1@dummy-tbig.id",
    action_date: "2025-11-05",
    remarks_internal: "Site rooftop Jakarta Selatan",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1038",
    vendor_name: "PT Antar Nusa Telekomunikasi",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2025-06-01T08:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0044/DUMMY-TBG/VEM-FO/06/VI/2025",
    period: "2025",
    contract_date_from: "2025-06-01",
    contract_date_to: "2026-06-01", // Expired
    draft_sent_date: "2025-05-15",
    draft_return_date: "2025-05-25",
    final_approval_date: "2025-05-29",
    return_to_vendor_date: "2025-06-03",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-06-05",
    remarks_internal: "Proyek penarikan kabel FO Palembang - Jambi",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1039",
    vendor_name: "CV Berkah Jaya Tehnik",
    core_business: "PERKUATAN",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2025-07-15T09:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0045/DUMMY-TBG/VEM-STR/07/VII/2025",
    period: "2025",
    contract_date_from: "2025-07-01",
    contract_date_to: "2026-01-31", // Expired
    draft_sent_date: "2025-06-18",
    draft_return_date: "2025-06-28",
    final_approval_date: "2025-06-30",
    return_to_vendor_date: "2025-07-04",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "contract.team@dummy-tbig.id",
    action_date: "2026-02-01",
    remarks_internal: "Penggantian sling dan turnbuckle",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1045",
    vendor_name: "PT Sentosa Abadi Fiber",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass - Deviation",
    rfc: "2025-09-01T11:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0046/DUMMY-TBG/VEM-FO/09/IX/2025",
    period: "2025",
    contract_date_from: "2025-09-01",
    contract_date_to: "2026-03-31", // Expired
    draft_sent_date: "2025-08-15",
    draft_return_date: "2025-08-25",
    final_approval_date: "2025-08-29",
    return_to_vendor_date: "2025-09-03",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "BELUM", // Scan belum
    upload_contract_status: "BELUM",
    outstanding_status: "Dokumen kontrak basah tercecer saat pindah gedung",
    action_status: "INACTIVE",
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2026-04-05",
    remarks_internal: "Pekerjaan tuntas tapi administrasi telat",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1047",
    vendor_name: "PT Mandiri Elektrika Solusi",
    core_business: "SUPPLY & INSTALL ICT",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2024-10-15T10:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0047/DUMMY-TBG/VEM-ICT/10/X/2024",
    period: "2024",
    contract_date_from: "2024-10-01",
    contract_date_to: "2025-10-01", // Expired
    draft_sent_date: "2024-09-15",
    draft_return_date: "2024-09-25",
    final_approval_date: "2024-09-29",
    return_to_vendor_date: "2024-10-03",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "contract.team@dummy-tbig.id",
    action_date: "2025-10-05",
    remarks_internal: "Penyelesaian garansi baterai",
    case_hold_terminate: null
  },
  {
    vendor_id: "VND-1048",
    vendor_name: "CV Wahana Tehnik Abadi",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2024-12-01T09:00:00.000Z",
    remarks_sourcing: "Renewal",
    contract_type: "P",
    contract_number: "0048/DUMMY-TBG/VEM-FO/12/XII/2024",
    period: "2024",
    contract_date_from: "2024-12-01",
    contract_date_to: "2025-12-01", // Expired
    draft_sent_date: "2024-11-12",
    draft_return_date: "2024-11-24",
    final_approval_date: "2024-11-28",
    return_to_vendor_date: "2024-12-03",
    contract_status: "Expired",
    subcont_status: "inactive",
    scan_doc_status: "SUDAH",
    upload_contract_status: "SUDAH",
    outstanding_status: null,
    action_status: "INACTIVE",
    pic_email: "vendor.ops@dummy-tbig.id",
    action_date: "2025-12-05",
    remarks_internal: "Penutupan buku kontrak 2025",
    case_hold_terminate: null
  },

  // 49-50: 2 Draft / No Contract Records
  {
    vendor_id: "VND-1049",
    vendor_name: "PT Solusi Jaringan Persada",
    core_business: "INSTALASI KABEL FO",
    vendor_category: "Small",
    result_selection: "Pass",
    rfc: "2026-09-15T09:00:00.000Z",
    remarks_sourcing: "New",
    contract_type: "P",
    contract_number: "0049/DRAFT-TBG/VEM-FO/09/IX/2026",
    period: "2026",
    contract_date_from: "2026-10-01",
    contract_date_to: null, // No contract
    draft_sent_date: "2026-09-18",
    draft_return_date: null,
    final_approval_date: null,
    return_to_vendor_date: null,
    contract_status: "No Contract",
    subcont_status: "inactive",
    scan_doc_status: "BELUM",
    upload_contract_status: "BELUM",
    outstanding_status: "Draft kontrak masih direview legal corporate",
    action_status: "HOLD",
    pic_email: "legal.operations@dummy-tbig.id",
    action_date: "2026-09-25",
    remarks_internal: "Tahap review klausul indemnifikasi oleh legal",
    case_hold_terminate: "Hold sementara menunggu klarifikasi tax"
  },
  {
    vendor_id: "VND-1050",
    vendor_name: "PT Anugerah Sarana Telekom",
    core_business: "SACME MACRO MICRO",
    vendor_category: "Small",
    result_selection: null,
    rfc: null,
    remarks_sourcing: "New",
    contract_type: "B",
    contract_number: "0050/DRAFT-TBG/VEM-SACME/08/VIII/2026",
    period: "2026",
    contract_date_from: "2026-08-01",
    contract_date_to: null, // No contract
    draft_sent_date: "2026-08-05",
    draft_return_date: null,
    final_approval_date: null,
    return_to_vendor_date: null,
    contract_status: "No Contract",
    subcont_status: "inactive",
    scan_doc_status: "BELUM",
    upload_contract_status: "BELUM",
    outstanding_status: "Gagal verifikasi dokumen legalitas perusahaan",
    action_status: "HOLD",
    pic_email: "vendor.management@dummy-tbig.id",
    action_date: "2026-08-20",
    remarks_internal: "Tidak lolos verifikasi NIB dan NPWP",
    case_hold_terminate: "Terminated pada tahap kualifikasi"
  }
];

if (dummyData.length !== 50) {
  console.error(`ERROR: dummyData length is ${dummyData.length}, expected exactly 50!`);
} else {
  console.log(`Verified: dummyData has EXACTLY ${dummyData.length} records.`);
}

module.exports = dummyData;
